In [1]:
import numpy as np

In [2]:
n1 = np.array([1, 2, 3, 4, 5])

In [3]:
n1

array([1, 2, 3, 4, 5])

In [4]:
type(n1)

numpy.ndarray

In [5]:
# creating array of zeros
z1 = np.zeros(5)
z1

array([0., 0., 0., 0., 0.])

In [6]:
# array of ones
o1 = np.ones(5)
o1

array([1., 1., 1., 1., 1.])

In [7]:
# range()
b1 = np.arange(1, 10)
b1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
b2 = np.eye(3)
b2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
# random
r1 = np.random.rand(4)
r1

array([0.10639263, 0.23962036, 0.22475761, 0.36118211])

In [10]:
# randn
r2 = np.random.randn(4)
r2

array([ 0.16508718, -1.95552749,  0.26808035,  2.19622563])

### To inspect the arrays

In [11]:
# to check the dimension of array (ndim)
o1.ndim

1

In [12]:
# shape
b1.shape

(9,)

In [13]:
b2.shape

(3, 3)

In [14]:
# size
b1.size

9

In [15]:
# dtype
b1.dtype

dtype('int64')

In [16]:
b2.dtype

dtype('float64')

### 2D array

In [17]:
a21 = np.array([[1, 2, 3], [4, 5, 6]])
a21

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
# 2d array of ones
a22 = np.ones([2, 3])
a22

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
# inspection
a22.size

6

In [20]:
a22.ndim

2

In [21]:
a22.shape

(2, 3)

### 3D Arryas

In [22]:
a3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
a3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [23]:
a3d.ndim

3

In [24]:
a3d.shape

(2, 2, 2)

In [25]:
# create a 3d array of shape (2,2,4)
b3d = np.array([[[1, 2, 3, 4], [4, 5, 6, 7]], [[1, 2, 3, 4], [4, 5, 6, 7]]])
b3d

array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[1, 2, 3, 4],
        [4, 5, 6, 7]]])

In [26]:
b3d.shape

(2, 2, 4)

In [27]:
c3d = np.array(
    [[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]], [[13, 14], [15, 16]]]
)

c3d

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]]])

In [28]:
c3d.shape

(4, 2, 2)

In [29]:
# 3d array of ones
ones3d = np.ones([2, 3, 4])
ones3d

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [30]:
ones3d.shape

(2, 3, 4)

### array manipulation

In [31]:
l1 = np.array([1, 2, 3, 4])
print(l1.shape)

(4,)


In [32]:
# reshape to another dimesion
l2 = np.reshape(l1, (2, 2))
l2

array([[1, 2],
       [3, 4]])

In [33]:
np.reshape(l2, (4,))

array([1, 2, 3, 4])

In [34]:
l2

array([[1, 2],
       [3, 4]])

In [35]:
l3 = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
l4 = np.reshape(l3, (4, 2))
l4

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [37]:
np.reshape(l3, (2, 2, 2))

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [38]:
# flatten - multi dimension to 1d
flatten_l4 = l4.flatten()
flatten_l4

array([1, 2, 3, 4, 5, 6, 7, 8])

In [39]:
# transpose
l4.transpose()

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [40]:
# concatenate()
array1 = np.array([4, 5, 6, 7])
array2 = np.array([1, 2, 3, 4])
joint_array = np.concatenate((array2, array1))
joint_array

array([1, 2, 3, 4, 4, 5, 6, 7])

In [41]:
# stack
np.stack((array1, array2), axis=1)

array([[4, 1],
       [5, 2],
       [6, 3],
       [7, 4]])

In [42]:
# vstack
np.vstack((array1, array2))

array([[4, 5, 6, 7],
       [1, 2, 3, 4]])

In [43]:
# split
array_a = np.array([1, 2, 3, 4])
np.split(array_a, 4)

[array([1]), array([2]), array([3]), array([4])]

In [44]:
# insert
np.insert(array_a, 2, 10)

array([ 1,  2, 10,  3,  4])

In [45]:
# delete
np.delete(array_a, 2)

array([1, 2, 4])

### Array operations

In [46]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])

In [47]:
# add
np.add(array1, array2)

array([ 7,  9, 11, 13, 15])

In [48]:
b1 = np.array([[1, 2, 3], [4, 5, 6]])
b2 = np.array([[7, 8, 9], [10, 11, 12]])

In [49]:
# add
np.add(b1, b2)

array([[ 8, 10, 12],
       [14, 16, 18]])

In [50]:
# others also there -> subtract, multiply, divide, power, mod, dot, cross

In [51]:
np.power(array1, array2)

array([      1,     128,    6561,  262144, 9765625])

In [52]:
# also can do :
array1 + 2

array([3, 4, 5, 6, 7])

In [53]:
array1 * 2

array([ 2,  4,  6,  8, 10])

### indexing and slicing

In [54]:
# indexing
array1[3]

np.int64(4)

In [55]:
# slicing
array1[1:3]

array([2, 3])

In [56]:
array1

array([1, 2, 3, 4, 5])

In [57]:
# where function
np.where(array1 > 2)

(array([2, 3, 4]),)

In [58]:
np.where(array1 >= 3, array1, 9)

array([9, 9, 3, 4, 5])

In [59]:
# take()
np.take(array1, [0, 4])

array([1, 5])

In [60]:
# argmax and argmin

np.argmax(array1)

np.int64(4)

In [61]:
np.argmin(array1)

np.int64(0)

In [62]:
# nonzero
np.nonzero(array1)

(array([0, 1, 2, 3, 4]),)

In [63]:
# stats functions: min, max, median, percentile
# math function: sin, cos, tan, exp, log, sqrt, ceil, floor